### ISSUE TITLE
SRTOD_CascadeRCNN is not in the mmdet::model registry.

### ISSUE THREAD

**Issue by AglaonemaCommutatum** [Hiyuur/SR-TOD#3]
您好，我在运行SRTOD_CascadeRCNN时报错`SRTOD_CascadeRCNN is not in the mmdet::model registry.`
下面是详细的报错信息：
```
Traceback (most recent call last):
  File "/home/msy/new/tools/train.py", line 133, in <module>
    main()
  File "/home/msy/new/tools/train.py", line 122, in main
    runner = Runner.from_cfg(cfg)
  File "/home/msy/anaconda3/envs/torch/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/home/msy/anaconda3/envs/torch/lib/python3.8/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/home/msy/anaconda3/envs/torch/lib/python3.8/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/home/msy/anaconda3/envs/torch/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/msy/anaconda3/envs/torch/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/msy/anaconda3/envs/torch/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'SRTOD_CascadeRCNN is not in the mmdet::model registry. Please check whether the value of `SRTOD_CascadeRCNN` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
ERROR conda.cli.main_run:execute(125): `conda run python /home/msy/new/tools/train.py /home/msy/new/srtod_project/srtod_cascade_rcnn/config/srtod-cascade-rcnn_r50_fpn_1x_coco.py` failed. (See above for error)
```
请问您也遇到类似的问题了吗，是怎么解决的

**Comment by Hiyuur** [comment]
您好，可以参考以下网页的信息来解决这个问题[https://blog.csdn.net/weixin_43978433/article/details/127863944](url)
